<div class="container">
    <h1>Cadastro de Musicos (Let's Rock)</h1>
</div>



<hr>
<div class="container">

    <form method="post" action="Request.php?class=app\controller\MusicoCtr&method=run">
        <input type="hidden" name="id" id="id" value="<?= $this->model->getId() ?>" ><br>
        <label for="nome">Nome:</label><br>
        <input type="text" name="nome" id="nome" value="<?= $this->model->getNome() ?>" required="required"><br>
        <label for="login">Login:</label><br>
        <input type="text" name="login" id="login" value="<?= $this->model->getLogin() ?>" required="required"><br>
        <label for="senha">Senha:</label><br>
        <input type="password" name="senha" id="senha" value="<?= $this->model->getSenha() ?>" required="required"><br>
        <label for="sexo">Sexo:</label><br>    
        <input type="radio" name="sexo" value="M" <?php if ($this->model->getSexo() == 'M') echo 'checked' ?>><label for="sexo">Masculino</label>    
        <input type="radio" name="sexo" value="F" <?php if ($this->model->getSexo() == 'F') echo 'checked' ?> ><label for="sexo">Feminino</label><br>
        <label for="cpf">CPF:</label><br>
        <input type="text" name="cpf" id="cpf" value="<?= $this->model->getCpf() ?>"><br>
        <label for="rg">RG:</label><br>
        <input type="text" name="rg" id="rg" value="<?= $this->model->getRg() ?>"><br>  

        <label>Banda:</label>
        <select name="banda">
            <?php
            $bandas = $this->bandas;
            foreach ($bandas as $banda) {
                if ($banda->getId() == $this->model->getBandaModel()->getId())
                    echo "<option selected value=\"{$banda->getId()}\">{$banda->getNome()}</option>";
                else
                    echo "<option value=\"{$banda->getId()}\">{$banda->getNome()}</option>";
            }
            ?>
        </select>
        <br>
        <input type="submit" name="comando" value="Novo">
        <input type="submit" name="comando" value="Salvar">
        <input type="submit" name="comando" value="Excluir">

    </form>
</div>

