<div class="container">
    <h1>Listar Musico</h1>
</div>
<hr>
<form method="post" action="Request.php?class=app\controller\MusicoCtr&method=showList">
    <label for="nome">Nome:</label>
    <input type="text" name="nome" id="nome">


    <label for="banda">Banda:</label>
    <select name="banda" id="banda">
        <option value="0">Todas</option>
        <?php
        foreach ($this->bandas as $banda) {
            ?>
            <option value="<?= $banda->getId() ?>"><?= $banda->getNome() ?></option>
            <?php
        }
        ?>
    </select>
    <label for="ordenar">Classificar por:</label>
    <select name="ordenar" id="ordenar">
        <option value="0">Nome do Integrante</option>
        <option value="1">Nome da Banda</option>
    </select>
    <input type="submit" name="comando" value="Listar">    
</form>

<table border="1" class="table table-striped table-bordered nowrap">
    <tr>
        <th>Nome</th><th>Sexo</th><th>CPF</th><th>RG</th><th>Banda</th><th>Visualizar</th><th>Relatorio</th>
    </tr>
    <?php
    if ($this->model) {
        foreach ($this->model as $musico) {
            ?>
            <tr>
                <td><?= $musico['nome'] ?></td>
                <td><?= $musico['sexo'] ?></td>
                <td><?= $musico['cpf'] ?></td>
                <td><?= $musico['rg'] ?></td>
                <td><?= $musico['banda'] ?></td>   
                <td><a href="Request.php?class=app\controller\MusicoCtr&method=showView&id=<?= $musico['id_pessoa_musico'] ?>">OK</a></td>
                <td><a href="Request.php?class=app\controller\MusicoCtr&method=showReport&id=<?= $musico['id_pessoa_musico']?>">Relatorio</a></td>

            </tr>
            <?php
        }
    }
    ?>
</table>


