<h1>Listar Clientes (Pessoa Física)</h1>
<hr>
<form method="post" action="Request.php?class=app\controller\PessoaFisicaCtr&method=showList">
    <label for="nome">Nome:</label>
    <input type="text" name="nome" id="nome">
    <input type="submit" name="comando" value="Listar">   
    <br>
</form>

<table border="1">
    <tr>
        <th>Nome</th><th>Sexo</th><th>Telefone</th><th>Cidade</th><th>Visualizar</th>
    </tr>
    <?php
    if ($this->model)
        foreach ($this->model as $pessoaFisica) {
            ?>
            <tr>
                <td><?= $pessoaFisica->getNome() ?></td>
                <td><?= $pessoaFisica->getSexo() ?></td>
                <td><?= $pessoaFisica->getTelefone01() ?></td>
                <td><?= $pessoaFisica->getCidade()->getNome() ?>/<?= $pessoaFisica->getCidade()->getUf() ?></td>
                <td><a href="Request.php?class=app\controller\PessoaFisicaCtr&method=showView&id=<?= $pessoaFisica->getId() ?>">OK</a></td>
            </tr>
            <?php
        }
    ?>
</table>