<h1>Listar cidades</h1>
<hr>
<form method="post" action="Request.php?class=app\controller\CidadeCtr&method=showList">
    <label for="nome">Nome:</label>
    <input type="text" name="nome">
    <input type="submit" name="comando" value="Listar">    
</form>

<table border="1">
    <tr>
        <th>Nome</th>
        <th>UF</th>
        <th>CEP</th>
        <th>Visualizar</th>
    </tr>
    <tr>
        <?php
        if ($this->model) {
            foreach ($this->model as $cidade) {
                ?>
                <tr>
                    <td><?=$cidade->getNome()?></td>
                    <td><?=$cidade->getUf()?></td>
                    <td><?=$cidade->getCep()?></td>
                    <td><a href="Request.php?class=app\controller\CidadeCtr&method=showView&id=<?=$cidade->getId()?>">OK</a></td>
                </tr>
            <?php
        }
    }
    ?>
</tr>
</table>
