<div class="container">
    <h1>Listar cidades</h1>
</div>
<hr>
<form method="post" action="Request.php?class=app\controller\CidadeCtr&method=showList">
    <label for="nome">Nome:</label>
    <input type="text" name="nome">
    <input type="submit" name="comando" value="Listar">    
</form>

<table border="1" class="table table-striped table-bordered nowrap">
    <tr>
        <th>Nome</th>
        <th>UF</th>
        <th>CEP</th>
        <th>Visualizar</th>
        <th>Relatorio</th>
    </tr>
    <tr>
        <?php
        if ($this->model) {
            foreach ($this->model as $cidade) {
                ?>
            <tr>
                <td><?= $cidade->getNome() ?></td>
                <td><?= $cidade->getUf() ?></td>
                <td><?= $cidade->getCep() ?></td>
                <td><a href="Request.php?class=app\controller\CidadeCtr&method=showView&id=<?= $cidade->getId() ?>">OK</a></td>
                <td><a href="Request.php?class=app\controller\CidadeCtr&method=showReport">Relatorio</a></td>
            </tr>
            <?php
        }
    }
    ?>
</tr>
</table>
