<h1>Cadastro de Clientes (Pessoa Juridica)</h1>
<hr>
<form method="post" action="Request.php?class=app\controller\PessoaJuridicaCtr&method=run">
    <input type="hidden" name="id" id="id" value="<?= $this->model->getId() ?>">
    <label for="nome">Nome:</label><br>
    <input type="text" name="nome" id="nome" value="<?= $this->model->getNome() ?>" required="required"><br>
    <label for="cnpj">CNPJ:</label><br>
    <input type="text" name="cnpj" id="cnpj" value="<?= $this->model->getCnpj() ?>"><br>
    <label for="setor">Função:</label><br>
    <input type="text" name="setor" id="setor" value="<?= $this->model->getFuncao() ?>"><br>
    <label for="razaosocial">Razão Social:</label><br>
    <input type="text" name="razaosocial" id="razaosocial" value="<?= $this->model->getRazaosocial() ?>"><br> 
    <label for="ramal">Numero Juridico:</label><br>
    <input type="text" name="ramal" id="ramal" value="<?= $this->model->getNumeroJuridico() ?>"><br> 
    <label for="endereco">Endereço:</label><br>
    <input type="text" name="endereco" id="endereco" value="<?= $this->model->getEndereco() ?>" required="required"><br>
    <label for="bairro">Bairro:</label><br>
    <input type="text" name="bairro" id="bairro" value="<?= $this->model->getBairro() ?>" required="required"><br>
    <label for="cidade">Cidade:</label><br>
    <select id="cidade" name="cidade">
        <?php
        foreach ($this->cidades as $cidade) {
            if ($this->model->getCidade()->getId() == $cidade->getId()) {
                ?>
                <option selected value="<?= $cidade->getId() ?>"><?= $cidade->getNome() . "/" . $cidade->getUf() ?></option>
                <?php
            } else {
                ?>
                <option value="<?= $cidade->getId() ?>"><?= $cidade->getNome() . "/" . $cidade->getUf() ?></option>
                <?php
            }
        }
        ?>
    </select><br>
    <label for="telefone01">Telefone01</label><br>
    <input type="text" name="telefone01" value="<?= $this->model->getTelefone01() ?>"><br>
    <label for="email">Email:</label><br>
    <input type="email" name="email" id="email" value="<?= $this->model->getEmail() ?>"><br>
    <input type="submit" name="comando" value="Novo">
    <input type="submit" name="comando" value="Salvar">
    <input type="submit" name="comando" value="Excluir">

</form>

