<h1>Listar Musicas </h1>
<hr>
<form method="post" action="Request.php?class=app\controller\MusicaCtr&method=showList">
    <label for="nome">Nome:</label>
    <input type="text" name="nome" id="nome">
    <input type="submit" name="comando" value="Listar">   
    <br>
</form>

<table border="1">
    <tr>
        <th>Nome</th><th>Duração</th><th>Album</th><th>Banda</th><th>Compositor</th><th>Visualizar</th>
    </tr>
    <?php
    if ($this->model)
        foreach ($this->model as $musicaModel) {
            ?>
            <tr>
                <td><?= $musicaModel->getNome() ?></td>
                <td><?= $musicaModel->getDuracao() ?></td>
                <td><?= $musicaModel->getAlbum() ?></td>
                <td><?= $musicaModel->getBanda()?></td>
                <td><?= $musicaModel->getCompositor()?></td>
                <td><a href="Request.php?class=app\controller\MusicaCtr&method=showView&id=<?= $musicaModel->getId() ?>">OK</a></td>
            </tr>
            <?php
        }
    ?>
</table>
