<h1>Listar Bandas</h1>
<hr>
<form method="post" action="Request.php?class=app\controller\BandaCtr&method=showList">
    <label for="nome">Nome:</label>
    <input type="text" name="nome">
    <input type="submit" name="comando" value="Listar">    
</form>

<table border="1">
    <tr>
        <th>Nome</th>
        <th>Intour</th>
        <th>Visualizar</th>
    </tr>
    <tr>
        <?php
        if ($this->model) {
            foreach ($this->model as $banda) {
                ?>
                <tr>
                    <td><?=$banda->getNome()?></td>
                    <td><?=$banda->getInTours()?></td>
                    <td><a href="Request.php?class=app\controller\BandaCtr&method=showView&id=<?=$banda->getId()?>">OK</a></td>
                </tr>
            <?php
        }
    }
    ?>
</tr>
</table>

