<div class="container">
    <h1>Listar Bandas</h1>
</div>
<hr>
<form method="post" action="Request.php?class=app\controller\BandaCtr&method=showList">
    <label for="nome">Nome:</label>
    <input type="text" name="nome">
    <input type="submit" name="comando" value="Listar"> 
    <a href="Request.php?class=app\controller\BandaCtr&method=showReport&id=all" value="Relatorio">
            <input type="button" name="comando" value="Relatorio"> 
    </a>
</form>


<table class="table table-striped table-bordered nowrap" border="1">
    <tr>
        <th>Nome</th>
        <th>Intour</th>
        <th>Visualizar</th>
        <th>Relatorio</th>
    </tr>
    <tr>
        <?php
        if ($this->model) {
            foreach ($this->model as $banda) {
                ?>
            <tr>
                <td><?= $banda->getNome() ?></td>
                <td><?= $banda->getInTours() ?></td>
                <td><a href="Request.php?class=app\controller\BandaCtr&method=showView&id=<?= $banda->getId() ?>">OK</a></td>
                <td><a href="Request.php?class=app\controller\BandaCtr&method=showReport&id=<?= $banda->getId() ?>">Relatorio</a></td>

            </tr>
            <?php
        }
    }
    ?>
</tr>
</table>

