<br>
<br>
<!-- Footer -->
<div class="navbar navbar-inverse navbar-fixed-bottom">
    <footer> 
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </footer>


</div>
<!-- /.container -->

<!-- jQuery -->
<script src="core/vendor/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="core/vendor/js/bootstrap.min.js"></script>


</body>

</html>