<!DOCTYPE html>
<?php session_start(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Logo Nav - Start Bootstrap Template</title>

        <!-- Bootstrap Core CSS -->
        <link href="core/vendor/css/bootstrap.min.css" rel="stylesheet">
        <script type="text/javascript" src="core/vendor/jquery-1.12.3.js"></script>

        <!-- Custom CSS -->
        <link href="core/vendor/css/logo-nav.css" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="http://localhost/GitHub/WebMusic/">
                        <img class="pull-left" src="core/vendor/img/logo12.png" alt="logo" height="66px" width="100px">
                    </a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="about.php">Sobre</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cadastro <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="Request.php?class=app\controller\MusicoCtr&method=showView">Musico</a></li>
                                <li><a href="Request.php?class=app\controller\BandaCtr&method=showView">Banda</a></li>
                                <li><a href="Request.php?class=app\controller\CidadeCtr&method=showView">Cidades em turnê</a></li>
                                <li><a href="Request.php?class=app\controller\MusicaCtr&method=showView">Musica</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Listagem <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="Request.php?class=app\controller\BandaCtr&method=showList">Banda</a></li>
                                <li><a href="Request.php?class=app\controller\MusicoCtr&method=showList">Musico</a></li>
                                <li><a href="Request.php?class=app\controller\CidadeCtr&method=showList">Cidades em turnê</a></li>
                                <li><a href="Request.php?class=app\controller\MusicaCtr&method=showList">Música</a></li>
                            </ul>
                        </li>
                    </ul>
                    <div class="pull-right">
                        <?php
                        if (isset($_SESSION['usuario'])) {
                            echo '<a href="Request.php?class=app\controller\MusicoCtr&method=LogUser&acao=Logout">Logout</a>';
                        } else {
                            header("location:http://localhost/GitHub/WebMusic/login.php");
                            echo ' <a class="pull-right" href="http://localhost/GitHub/WebMusic/login.php">Login</a>';
                        }
                        ?>
                    </div>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>







        <!--  <ul> 
              <li>Cadastrar
                  <ul>
                      <li><a href="Request.php?class=app\controller\MusicoCtr&method=showView">Musico</a></li>
                      <li><a href="Request.php?class=app\controller\BandaCtr&method=showView">Banda</a></li>
                      <li><a href="Request.php?class=app\controller\CidadeCtr&method=showView">Cidades em turnê</a></li>
                      <li><a href="Request.php?class=app\controller\MusicaCtr&method=showView">Musica</a></li>
                  </ul>
              </li>
              <li>Listar
                  <ul>
                      <li><a href="Request.php?class=app\controller\BandaCtr&method=showList">Banda</a></li>
                      <li><a href="Request.php?class=app\controller\MusicoCtr&method=showList">Musico</a></li>
                      <li><a href="Request.php?class=app\controller\CidadeCtr&method=showList">Cidades em turnê</a></li>
                      <li><a href="Request.php?class=app\controller\MusicaCtr&method=showList">Música</a></li>
  
                  </ul>                         
              </li>
          </ul>                   
      </nav> -->



